# use try rescue else after

The purpose of this exercise is to use the `try..rescue..else..after` construct. While there are certainly other ways to approach this problem, please use this one here.
